name: charity_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  dropdown_button2: ^2.3.9
  easy_search_bar: ^2.5.0
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1
  carousel_slider: ^4.2.1
  flutter_stripe: ^10.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: arslan
      fonts:
        - asset: fonts/Arslan-Wessam-B.ttf
