name: charity_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  dropdown_button2: ^2.3.9
  easy_search_bar: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image 3.png
    - assets/pp.png
    - assets/image 4.png
    - assets/image 5.png
    - assets/google.png
    - assets/facebook.png
    - assets/home.svg
    - assets/donate.svg
    - assets/profile.svg
    - assets/cart.svg
    - assets/location.svg
    - assets/Bell.svg
    - assets/logout.svg
    - assets/support.svg
    - assets/setting.svg
    - assets/wallet.svg
    - assets/list.svg
    - assets/password.svg
    - assets/lang.svg
  fonts:
    - family: arslan
      fonts:
        - asset: fonts/Arslan-Wessam-B.ttf
