// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRmJh3qrFfZpQz8OMrpjDjHhn5chxaXM',
    appId: '1:536882463537:web:c70c7467035db3972b6610',
    messagingSenderId: '536882463537',
    projectId: 's7ety-2bde7',
    authDomain: 's7ety-2bde7.firebaseapp.com',
    storageBucket: 's7ety-2bde7.appspot.com',
    measurementId: 'G-TSFNXZH8GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6JAcK7wWi4vQAbKAbT4u3iIc42vQbYvc',
    appId: '1:536882463537:android:43fb641d16ba4cd32b6610',
    messagingSenderId: '536882463537',
    projectId: 's7ety-2bde7',
    storageBucket: 's7ety-2bde7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzJzvlmSBYCWrGjtM4SUL6r2TyIc_2_v4',
    appId: '1:536882463537:ios:a4c8ed443070330e2b6610',
    messagingSenderId: '536882463537',
    projectId: 's7ety-2bde7',
    storageBucket: 's7ety-2bde7.appspot.com',
    iosBundleId: 'com.example.s7ety',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzJzvlmSBYCWrGjtM4SUL6r2TyIc_2_v4',
    appId: '1:536882463537:ios:a4c8ed443070330e2b6610',
    messagingSenderId: '536882463537',
    projectId: 's7ety-2bde7',
    storageBucket: 's7ety-2bde7.appspot.com',
    iosBundleId: 'com.example.s7ety',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoRmJh3qrFfZpQz8OMrpjDjHhn5chxaXM',
    appId: '1:536882463537:web:4b4bf0643eb4a27d2b6610',
    messagingSenderId: '536882463537',
    projectId: 's7ety-2bde7',
    authDomain: 's7ety-2bde7.firebaseapp.com',
    storageBucket: 's7ety-2bde7.appspot.com',
    measurementId: 'G-8R5Q6RMDNR',
  );
}
